[package]
name = "knot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.18", features = ["form", "tracing", "macros", "headers", "multipart"] }
axum-extra = { version = "0.7.4", features = ["form"] }
chrono = { version = "0.4.24", features = ["rkyv", "serde", "clock"] }
chrono-tz = "0.8.2"
icalendar = { version = "0.15.4", features = ["chrono-tz"] }
time = "0.3.21"
dotenvy = "0.15.7"
liquid = "0.26.1"
serde = "1.0.163"
sqlx = { version = "0.6.3", features = ["runtime-tokio-rustls", "postgres", "macros", "offline", "chrono"] }
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"] }
tokio-util = { version = "0.7.8", features = ["io"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
tracing-tree = "0.2.3"
walkdir = "2.3.3"
image = "0.24.6"
rand = "0.8.5"
async_zip = { version = "0.0.15", features = ["tokio", "tokio-fs", "deflate"] }
csv-async = { version = "1.2.6", features = ["tokio"] }
tower-http = { version = "0.4.0", features = ["trace"] }
rust_xlsxwriter = "0.39.0"
axum-login = { version = "0.5.0", features = ["sqlx", "postgres"] }
bcrypt = "0.14.0"
eyre = "0.6.8"
once_cell = "1.17.1"
new_mime_guess = { version = "4.0.1", default-features = false }
