[package]
name = "knot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.18", features = ["form", "tracing", "macros"] }
axum-extra = { version = "0.7.4", features = ["form"] }
chrono = { version = "0.4.24", features = ["rkyv", "serde"] }
dotenvy = "0.15.7"
icalendar = "0.15.4"
liquid = "0.26.1"
serde = "1.0.162"
sqlx = { version = "0.6.3", features = ["runtime-tokio-rustls", "postgres", "macros", "offline", "chrono"] }
thiserror = "1.0.40"
tokio = { version = "1.28.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
tracing-tree = "0.2.3"
walkdir = "2.3.3"
